keys:
  age:
    - &self0 age1yubikey1qt4k5tkk47fm58cj66s7cr8z9mete4jkyv2xjdfexcfwc0cw9c9jx7xgpwc
    - &self1 age1wg5kd692d3m4mh83qt5smzeu48j8w2gjspxk4l5svlg92fumqefqvkp3kx
    - &flandre-m5p age18ktzczpaufkp34j42plxlyl94yu3tusvpad6mfperpw7stypdfxqdn4au8
    - &marisa-7d76 age1zufm5x7xk8xt3pfzfkdj60z9sd7vnmq739udpwwp4h8qd7nujqesusm4vq
    - &marisa-j715 age1mc0nfucl68cswqd9xkcmv4l003wan84yked7tspsjtl4ya40p99q6sx9l3
    - &reisen-ams0 age1033cpzwt608pslj3fn7pqgx2cnsd9rvr5tnzwhmn89tuvsd90els8xxjgm
    - &reisen-nrt0 age1yn8a3m66ccsgdgp9fnguavnx3hz9e0wwz594jk0v8hhq84rs8utq4ggtww
    - &reisen-sea0 age1cy0r5j5m4r98srahv0g6tr4xxhc543sc577y3f49vya7sxs5es4sldp0vt
    - &reisen-sin0 age10jyxva6hwwesdckff5xuhk8d9askpqc605spfxjxpvsqtllqgeps6q9s9m
    - &kogasa-iad0 age1q5rv9w3e33xhkjyacnwjrxe4asm4t6wkpqlstq6ryxherx4f04hsz99t07
    - &suwako-vie0 age1myxcefjtnhtjsnvh9w9ntzqncgu02l4lg27gvqna2te3nflz4vlqj7nmer
    - &suwako-vie1 age10facvdx4y8q8rz9fpf2w566283e9nglhx9tkr90e6uetem8hkyaqffqqa9
    - &kanako-ham0 age1qdunuzv0wwn2xqgt54s64v28488gsz4ky7u5zcv4yt26n7wn8gesx3x3za
creation_rules:
  - path_regex: infra/.*
    key_groups:
      - age:
          - *self0
          - *self1
  - path_regex: secrets/common.*
    key_groups:
      - age:
          - *self0
          - *self1
          - *flandre-m5p
          - *marisa-7d76
          - *marisa-j715
          - *reisen-ams0
          - *reisen-nrt0
          - *reisen-sea0
          - *reisen-sin0
          - *kogasa-iad0
          - *suwako-vie0
          - *suwako-vie1
          - *kanako-ham0
  - path_regex: secrets/hosts/(opentofu/)?flandre-m5p
    key_groups:
      - age:
          - *self0
          - *self1
          - *flandre-m5p
  - path_regex: secrets/hosts/(opentofu/)?marisa-7d76
    key_groups:
      - age:
          - *self0
          - *self1
          - *marisa-7d76
  - path_regex: secrets/hosts/(opentofu/)?marisa-j715
    key_groups:
      - age:
          - *self0
          - *self1
          - *marisa-j715
  - path_regex: secrets/hosts/(opentofu/)?reisen-ams0
    key_groups:
      - age:
          - *self0
          - *self1
          - *reisen-ams0
  - path_regex: secrets/hosts/(opentofu/)?reisen-nrt0
    key_groups:
      - age:
          - *self0
          - *self1
          - *reisen-nrt0
  - path_regex: secrets/hosts/(opentofu/)?reisen-sea0
    key_groups:
      - age:
          - *self0
          - *self1
          - *reisen-sea0
  - path_regex: secrets/hosts/(opentofu/)?reisen-sin0
    key_groups:
      - age:
          - *self0
          - *self1
          - *reisen-sin0
  - path_regex: secrets/hosts/(opentofu/)?kogasa-iad0
    key_groups:
      - age:
          - *self0
          - *self1
          - *kogasa-iad0
  - path_regex: secrets/hosts/(opentofu/)?suwako-vie0
    key_groups:
      - age:
          - *self0
          - *self1
          - *suwako-vie0
  - path_regex: secrets/hosts/(opentofu/)?suwako-vie1
    key_groups:
      - age:
          - *self0
          - *self1
          - *suwako-vie1
  - path_regex: secrets/hosts/(opentofu/)?kanako-ham0
    key_groups:
      - age:
          - *self0
          - *self1
          - *kanako-ham0
