nixos:
  kogasa-iad0: ENC[AES256_GCM,data:ckgZCMyeRzJ/0v/gYCbTWa/h8sjtnVis7abmI0OkBDwLECEwBTDFsF9FgT60RYX7tSheTs4Zov+bHJXs0SBq664mmxGJ6iM/F8uB6f6al92Ko5SoDZpIXu8v2oR9IaSx6DEu46ru1xGLxWZlwabSBCKga5Rh/vFgWvO68m6wD6OVKJ97AEsZ9aw867hgxBe35o5RYfCNSa2OBx7QmNNbQfCKJTEQT23lXEvGgP4W+XRzOMi6eVkrYlFtaaxV,iv:uCkBTUMBRwqgQDAjVflBqqIqInObHzlv2ywvMyEzMf4=,tag:e+MLR/QRvuAYmSqP//mv6Q==,type:str]
tofu: ENC[AES256_GCM,data:wv2zsYRcwM8boVYSaH4EtI4poL/modLixJ8gDoP1T7+JLDyCRyZQsu6WkMR9JPJrRsbMvQ2tFFrk8LPZU2hhh6BqqPX/ZlYUAmAQACuZa1JnUYeskc2TLVNkaL9Glz+cpfylyHQr0ARwEw5Q/cWdC1Xg55pnRFmVOQSY9Sf9asE6fxZ0JIAMPQeVTCe+CQ==,iv:O3smIEUNBPh4pAGUgbnKqLrqjCCK+ZRzVa9mnx9P4s0=,tag:Iv8UFwnUKTUgU+YFQ3gaqg==,type:str]
b2:
  application_key_id: ENC[AES256_GCM,data:/d5o2E1AH9We5PO3Z6ht4gmWTYaIEi3SBQ==,iv:M01vQK8e0Vz47d3aSIf+ZBru5yKrI4RF2dWIt0QigXo=,tag:psl7KFArqDmewMtae0vxzw==,type:str]
  application_key: ENC[AES256_GCM,data:ilAp9RHqgIZdojHr0DWOJSf0Fa6/H9f8/pPKQ9tvCg==,iv:Vi8+s2zREguZPjkFkGcKzVRaRHKlXKQcU7fsLiNo48c=,tag:xlhWxf+ObzIUdu3D5CON+A==,type:str]
vultr:
  api_key: ENC[AES256_GCM,data:V0As2kf9MB+/CAgwvwm9dTtP7KAQb59NLtyw2uR2KGnz40O8,iv:+LbAtZ1bg1pzyomsao6/w5iK21LLepSK/hupONkuoHE=,tag:67hvdoorzk40VeW6FwPTRg==,type:str]
sops:
  age:
    - recipient: age1sfnct03u4cvfj98x4yjrcrrnu5gg8qgxrwk4uqq8w4e6wveeaedq97rn44
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArdnlvV09oUWNERmJyM0ZW
        WStza2xMdm1JTVRzR0ZBcFlwOFdxamZQMmdZCkVIZG1HOVNla3RQbjRzNmlUUDRX
        YitxTXQwUVUzb1JHbEI3NFlMbjI0MmMKLS0tIDRkdjhCcWRNYTkyYWJwUmZENjh3
        Rk1mSHZicDNuVVFpL1NMcS9NS0NmRXcKT2GiNJ8L2ADuoJPm5XF1SrkNZtEzh/i5
        8gGmswWnE+d7VM0BSnM64la/E4prcIhM4e4Ybyd8El6pwQN919gofQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-10T16:03:36Z"
  mac: ENC[AES256_GCM,data:mQ6BNrSGoHXLr6+jiLis/7swwrANtVKs9mL31YFI3jJM1y6YtyvxUHjcY2CC7oahUAiw27uaJCAQiDMK0fIOfN1Gjj8kHbtqX4tCJOiFXhrFW8XRlo5GOsnuMSyp7X/KwCVV7vi8dsnYRRwbpXS7fPgo7AUeOgo5+FRAMJZrZyo=,iv:JqVLyGdD3C7vAnQc+fQseH7rn3Pbb8eMmZ5JJycmRnY=,tag:LBeMwiNUPsidgAOLRRGG9w==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.10.2
