tofu: ENC[AES256_GCM,data:wv2zsYRcwM8boVYSaH4EtI4poL/modLixJ8gDoP1T7+JLDyCRyZQsu6WkMR9JPJrRsbMvQ2tFFrk8LPZU2hhh6BqqPX/ZlYUAmAQACuZa1JnUYeskc2TLVNkaL9Glz+cpfylyHQr0ARwEw5Q/cWdC1Xg55pnRFmVOQSY9Sf9asE6fxZ0JIAMPQeVTCe+CQ==,iv:O3smIEUNBPh4pAGUgbnKqLrqjCCK+ZRzVa9mnx9P4s0=,tag:Iv8UFwnUKTUgU+YFQ3gaqg==,type:str]
cloudflare:
  api_token: ENC[AES256_GCM,data:7M6Lr5YADfgzSVsDNRNFWnB5mOwkMuMJmJ/+a7Dc0voZuqJs4tN9dQ==,iv:Kw3Q0D+dZqOowFNhIaFC4DtpD6fIDNuI1AqgzDOW1SA=,tag:Zk4Rjvn7BJAc/bpUZfERxA==,type:str]
  account_id: ENC[AES256_GCM,data:sLf/0k/YigCNmuMmJs1oAC0RH33kk/LEYyQ0mTCmGx8=,iv:/aLFeJ6CMUEF13jq/uH/qF+uh/Iw0exXaIiN2KLyiTM=,tag:JODPvMIOKwS1Hiv2u6HQ+A==,type:str]
  zone_id: ENC[AES256_GCM,data:iq4Gq3/+DsEVefEmo0wIHkokhi/1EbkVHWiXOdJdCFA=,iv:8CyDCjvVGyg0ekzr9LW3vIWKxjkx8uBP8Rv6i1dxUbE=,tag:+L9tbPbZ4YS4wy8fwmPKLg==,type:str]
b2:
  application_key_id: ENC[AES256_GCM,data:/d5o2E1AH9We5PO3Z6ht4gmWTYaIEi3SBQ==,iv:M01vQK8e0Vz47d3aSIf+ZBru5yKrI4RF2dWIt0QigXo=,tag:psl7KFArqDmewMtae0vxzw==,type:str]
  application_key: ENC[AES256_GCM,data:ilAp9RHqgIZdojHr0DWOJSf0Fa6/H9f8/pPKQ9tvCg==,iv:Vi8+s2zREguZPjkFkGcKzVRaRHKlXKQcU7fsLiNo48c=,tag:xlhWxf+ObzIUdu3D5CON+A==,type:str]
vultr:
  api_key: ENC[AES256_GCM,data:V0As2kf9MB+/CAgwvwm9dTtP7KAQb59NLtyw2uR2KGnz40O8,iv:+LbAtZ1bg1pzyomsao6/w5iK21LLepSK/hupONkuoHE=,tag:67hvdoorzk40VeW6FwPTRg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1sfnct03u4cvfj98x4yjrcrrnu5gg8qgxrwk4uqq8w4e6wveeaedq97rn44
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArdnlvV09oUWNERmJyM0ZW
        WStza2xMdm1JTVRzR0ZBcFlwOFdxamZQMmdZCkVIZG1HOVNla3RQbjRzNmlUUDRX
        YitxTXQwUVUzb1JHbEI3NFlMbjI0MmMKLS0tIDRkdjhCcWRNYTkyYWJwUmZENjh3
        Rk1mSHZicDNuVVFpL1NMcS9NS0NmRXcKT2GiNJ8L2ADuoJPm5XF1SrkNZtEzh/i5
        8gGmswWnE+d7VM0BSnM64la/E4prcIhM4e4Ybyd8El6pwQN919gofQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-15T08:14:49Z"
  mac: ENC[AES256_GCM,data:7LnhoiwQxTfVOJD2aa46LFx5Z6s5Ao7E1VDFKyxl1tDc7HpjaS+M8nT/8VJbOP47Yakd0Pduhglz9V0KjOM8BTuKge1ZHCHRBhjMpOgqNI0PkAbnEZNUn+/x6jBv9e4ezdQNUo0PWk8OKsnfEePVZY/qFWLiZGlgtOS1ewjn+OI=,iv:9ihcNEreTALacsk5P6lNiPgEHMIjIu36FdRYJ+znsdg=,tag:Qys/PmeCq3cmUI4iGYhLWg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
