scheme = "Adwaita Dark"
variant = "dark"

[palette]
base00 = "#1e1e1e"
base01 = "#241f31"
base02 = "#5e5c64"
base03 = "#c0bfbc"
base04 = "#f6f5f4"
base05 = "#ffffff"
base06 = "#c061cb"
base07 = "#4fd2fd"
base08 = "#c01c28"
base09 = "#f5c211"
base0A = "#f8e45c"
base0B = "#2ec27e"
base0C = "#0ab9dc"
base0D = "#1e78e4"
base0E = "#9841bb"
base0F = "#ed333b"
base10 = "#241f31"
base11 = "#ed333b"
base12 = "#57e389"
base13 = "#f8e45c"
base14 = "#51a1ff"
base15 = "#c061cb"
base16 = "#4fd2fd"
base17 = "#f6f5f4"
