scheme = "Adwaita Lark"
variant = "light"

[palette]
base00 = "#ffffff"
base01 = "#f6f5f4"
base02 = "#c0bfbc"
base03 = "#5e5c64"
base04 = "#241f31"
base05 = "#000000"
base06 = "#a8a8a8"
base07 = "#e8e8e8"
base08 = "#b61c24"
base09 = "#d4ae00"
base0A = "#e6d95c"
base0B = "#2ba86b"
base0C = "#0aa0c0"
base0D = "#1e70cc"
base0E = "#8c3fae"
base0F = "#d02028"
base10 = "#2e2e2e"
base11 = "#d02028"
base12 = "#47c880"
base13 = "#e6d95c"
base14 = "#3a90f0"
base15 = "#ac60cc"
base16 = "#3ec0e0"
base17 = "#e8e8e8"
