wireless:
  edu: ENC[AES256_GCM,data:pJywIoTlEBSeAiSbLxKhmMHSM6Jl+hlAQJcwN35wTySgjKp0bavwe12lUmRh9uqYsD0dOqylEp+E8k2RqnKv7tTa8o90m8sfLDYbnZhcxc6b5PqLqrOy1w/kt1Yyalw2lF0L7kHxwJIMw0AOzbvTCo4MJJ6fP60o1qufGehDWkbTfruo1ykoFZ7XHxsDTgnx0cmXdN14R8dzx42Sb6XyVRHcJuuIelN619gojgmJERRjdDwpU4RuhpdNxXT0FizMxPW401tQFGuLzveUTghjDe29YKiNquN9ZKU=,iv:PCB19C+7xwKirjcd7kwa3HP4Vv18dO0KcZfATJoT8Gg=,tag:CcM5zX5tyHl/xqT2r2f5qQ==,type:str]
user-password:
  rebmit: ENC[AES256_GCM,data:0gVXGbkY5W2GWSZF2WBVS2tySstaxQ4iTcBbXheT1lGYrk3VMXzK3bYgwqndsZJoHTz4ik99apiFgGn9B1BqFVosFfTNmNqnVw==,iv:5wgcAgNgv68iKLLcP/UzWXihvN1/vMBkyIAws+AoXAs=,tag:95QDKOY012ifSwpJyRlJJw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1sfnct03u4cvfj98x4yjrcrrnu5gg8qgxrwk4uqq8w4e6wveeaedq97rn44
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBU0pFeEhobHRBcHluV1Np
        bXBGUzlNV3JRRkNNNisxYWhNWTlicldYNWdRClBVQWhGVmpLYzM2TUlrMFdRRllV
        RGhsWmw5WWVMaXAwdXpKODVldi9rakEKLS0tIEQrc3VyVjVkb0hUZDRpUDZKTTNN
        Q2k2RTIrM1BrSFdnOVQ2SkpFNFBKS2cKwd5Qq51jrbTVIC1LTaB2lLgJuOIQ+LUb
        Z0eHZSvAE9hfim2eBvGXwKwR36nrEtySYhaG/Ho1QmVncgD3CI0xVw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age166kxtrcx99fxlgtvz5mvyt5ctvk3dt09f42gvm94ngnkyztmmelsyzdn77
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4N243NmM3SDI3ZmpVN2V5
        QVY5V0dQajVrWitqSEJaMjdFT3J2SjVUNnc0CnRaV3EwYnRqQmM0VGJ5UjBCbUdn
        VGhMaXlzUkk3K3hRQzhOazhoOUVieUEKLS0tIFZFQ3lpNFNvaTV5UlRIdGpId3E3
        RlFlbHVGcS9FaXAxa2duQXJBVWFlY1UKCuD0GMf/CzeGaGZKxCaNdaYCOplpv9lx
        rWKn3wGi8FHkJVj85U8Nl99uN64nwfTh+8MB8GXNwG0fv/jjVRiWfA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-11-02T06:58:25Z"
  mac: ENC[AES256_GCM,data:bVj4YD7lmQrs1pbES0CbnnbcCbcTCfUCF3PKUwWTqMJqDCbDchIFc0u+5drdDU8XevStUa6lNq/Ffu2GXoDjt3ybXYt22GJ9RN6ADXKSvNwzjIM4JYp9lxEwp5Z5StxM0/F7PBx3n+DJfsRM4xkRnZQ3cNJAYYl4KevDL0naOsY=,iv:YFV+MdpJQUN/Powqr37PfVPHUQl9kO2tkZSAldZAGOM=,tag:DGoedXDQqYc+jxE0hfP4uQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.0
