wireless:
  edu: ENC[AES256_GCM,data:0jDmQTpU8edTehG8b+cf2ENGgib+4ZxQBvYN6mPyC8VI7EvKTmsvRfwISAtcibyhZBeWc2ZhhSXmQnXu4FW716W1LUgfPVlNXV/NEon9b+5/Xr6J+6SSjq3rzvwTvkfEZg5mb5RWgJtW+0Esp8jGsWcsPN8O6Yi5UgooggSaxPWqN4riuDy74yxm6wle+wjKKlQo7cEcQB2oOWbn+tlfnjs/zK39Ro3RggVGMMYQwcCePZkyhOBIshDOQQablwTgTHkTAonv3YdgMVbTAicengzJkkHi5pTUtf8=,iv:/aNpz7M4HFahyy7DT5F802L/5VaQqGdtZmW2JF2CDVE=,tag:P8x060i2fiT4UFT+PIYoFQ==,type:str]
user-password:
  rebmit: ENC[AES256_GCM,data:getIARmyfQZp/NydtWAI6HJsJRoP2N8+mLVDjWLxmH59ijvWhwOcIBLSvaFudcH9pkc11NgEmD7Qmt/koLzTocCzeJu22tEC9w==,iv:15pBx5p1vsOqnvZtSDKRZFVau/Ciqa2F5dra9l34AOw=,tag:dbpiQOg2+A3Dpk5c8KvBBA==,type:str]
sops:
  age:
    - recipient: age1sfnct03u4cvfj98x4yjrcrrnu5gg8qgxrwk4uqq8w4e6wveeaedq97rn44
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjNFBPQUFPTlQ5Sk5FbHJk
        MDhsTUtBTlZqUmhwS3h5Zk5EZ29rNi84alNBClJLWTNISGwvTU9YT0dob2orR1Jt
        QlJwdnEvbjRBUlBpSUlvQi8rclJGRDgKLS0tIGdKL3g3eUFiNHFnTytsRmJrSkdC
        RHZQNUZTQm04cFhtMlBnQkQvWHNaeFkK6oNvRQIR3/9gSMjg2uhdT5U+YOpHHkL0
        TOJIeymdWU8jUD6IYd9IUbrIz9kQqaAFmFIRczyx+YIgHQ0YloLBgw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1k0vxl79ulfjsmpk48crm5fsuepyhgvjgg9nqtt38ffz7wp3em96scvgkuh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Zy9xd3RVbm1WRXg5LzYx
        N1R5NlAyS29UTmhKNE1NVXlrK0pzNDMxZUVvCjE4V2s0aW1Lc0x6WHBERlplS1JD
        emI1dmNuT2pXbXdQSTRoYVR2TEdjSFUKLS0tIEZYVXpzcVRKS1Vsb3ZQd2x4Rnpa
        MkQ0bE1rZitlUnZld0xZNnN5dkwxcVEKO7tRMVHcs17h5ZHOqly6ldywfIeXHh6q
        lhNJ1gzIU9UYvyuWy9WWxffmx9vV9bHByeBypswK7VVM6/acvusbEA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1w66uztjxshlg5yvt9qfkwsassqlzthqlt8zs626h9jqns56xpqqq3xcqqw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBbkFYbDV3UVA2V1NlcGtT
        UzlRNnh6eVh4S0h1emUvT01xWVFwWUtQSnk0CnZxTHM1UWphOHM4SnNQMzlsWTFU
        ZnhDalVxdTlOMFFTdGN5YzArN0c1cGcKLS0tIEI3YytGY3lpYkFvZXp4dlRFc1Jh
        Y3NsR21RaHdxWWE5UnpLd0NxM3NNS0kKG3TA1R2+vFEXnY0bbb9Kay80QFGCOa1I
        yqOYtIJ/Xk6A8MNAEEGlpusaYJr7OPDSlgRptB2k8xWrOD7GxCkVTA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1vv2l70nrplhhw0x65yvsf00gmrnfw5myqdeczzu3p5ltx54tzpgq0nhx2c
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpM3BkaEZONU5PeUUzTzgz
        WmV3UTF4ZG1QUkp6QXpFMGMvcXFTanhrQXh3CkxSamJnY2RsK2FOaEtGQVp0dVdx
        NkIwQWsrL213bFlQemhTV2dST3U3NHMKLS0tIDZrY3FjL2o1ZjBmbEhrcHV1cVBN
        SVJMbWc4OGhCc2l4Y3RzcjZGekNVR1EKex4okwK0QozSaa8eiOICuKrZGLuTjw/X
        7cvDB5fT8tvNJxNM0EJmWjFGmXNuBxraxVMeNnNJLWKt869sSwofdQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-01T14:03:04Z"
  mac: ENC[AES256_GCM,data:YAtv3diegNQ2V6ao8wU9XTO3mohzFwGpPWWcYFn5Yi2T+3BVrOkWbGKdR+kUkNX6Y2E+UjS0hkMbHx08XO54cDaLHa9+evVgGVrT8DYP3ljdn2dOk/VacEH3qoe+vlpMZtdOBLI6kYGz280+T4T5qPlv6Ghry94aiPrLlaAxIPA=,iv:pMEC/OOZe3EQfWr/8VxUo0nqq5gSF6w1LKCfz2V02ok=,tag:LGeOgopLgbhWFJsBrVePiw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.10.2
